### ISSUE TITLE
'module' object has no attribute 'Tuner'

### ISSUE THREAD

**Issue by ajman098** [ederwander/PyAutoTune#1]
Got install working on Debian 7.0. When I run your basic example the program hangs. In the shell I get the following error. I'm not the most experienced at this, so I will be happy to admit user error if I'm messing up somehow.

```
Traceback (most recent call last):
File "/home/pi/python/PyAutoTune-master/Examples/AutoTune.py", line 7, in <module>
import AutoTune
  File "/home/pi/python/PyAutoTune-master/Examples/AutoTune.py", line 54, in <module>

rawfromC=AutoTune.Tuner(Signal,FS,CHUNK,SCALE_ROTATE,SCALE_ROTATE,LFO_QUANT,CONCERT_A,FIXED_PITCH,FIXED_PULL,CORR_STR,CORR_SMOOTH,PITCH_SHIFT,LFO_DEPTH,LFO_RATE,LFO_SHAPE,LFO_SYMM,FORM_WARP,MIX,KEY)
AttributeError: 'module' object has no attribute 'Tuner'
```
